name: api_spec_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  api_spec:
    path: ../api_spec

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
